name: Node.js CI

on:
  push:
    branches: [ feature ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: "Build and test"  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm install -g bats
      - run: echo ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
